// Responsive image helpers: every large WebP has a `-768.webp` mobile sibling
// generated by scripts/optimize_images.cjs. Phones download the small one.

// Bundled images get hashed filenames, so map full-size URL -> mobile URL at build time
const bundled = import.meta.glob('../assets/images/*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>;

const mobileByUrl: Record<string, string> = {};
for (const [file, url] of Object.entries(bundled)) {
  const mobile = bundled[file.replace(/\.webp$/, '-768.webp')];
  if (mobile) mobileByUrl[url] = mobile;
}

// Public images (served as-is) that have a mobile sibling
const PUBLIC_WITH_MOBILE = new Set([
  '/images/about_chauffeur_vip.webp',
  '/images/about_discretion_vip.webp',
  '/images/fleet_cadillac_escalade_1791294159140.webp',
  '/images/fleet_png/cadillac_lyriq_electric.webp',
  '/images/service_airport_transfer_1791294128362.webp',
  '/images/service_corporate_travel_1791294137972.webp',
  '/images/service_special_events_1791294148674.webp',
  '/client_assets/chauffeur-voiture-de-luxe.webp',
  '/client_assets/service-limo.webp',
]);

const mobileUrl = (src: string): string | undefined =>
  mobileByUrl[src] ?? (PUBLIC_WITH_MOBILE.has(src) ? src.replace(/\.webp$/, '-768.webp') : undefined);

/** srcSet for an image that has a mobile variant, otherwise undefined (plain src is used). */
export const srcSetFor = (src: string): string | undefined => {
  const mobile = mobileUrl(src);
  return mobile ? `${mobile} 768w, ${src} 1376w` : undefined;
};

/** Warm the browser cache so a subpage's images are ready before it opens. */
const preloaded = new Set<string>();
export const preloadImages = (urls: string[]) => {
  for (const url of urls) {
    if (!url || preloaded.has(url)) continue;
    preloaded.add(url);
    const img = new Image();
    img.decoding = 'async';
    img.src = url;
  }
};
